### ISSUE TITLE
Add a new row when pressing Enter key

### ISSUE THREAD

**Issue by daviwesley** [iddan/react-spreadsheet#100]
```javascript
const [initialData, setInitialData] = useState(data);
...
<Spreadsheet
        data={initialData}
        onKeyDown={(e) => {
          if (e.key === "Enter") {
            setInitialData((prev) => prev.concat([[{ value: "" }]]));
          }
        }}
 />
```
I'm trying this code on the OnKeyDown to add a new row in fact it is adding a new row but it is erasing all the previous data

**Comment by iddan** [comment]
Can you provide a codesandbox please?

**Comment by daviwesley** [comment]
I can't run the code on codesandbox but this exactly all my code
https://codesandbox.io/s/cold-haze-2ill5

**Comment by iddan** [comment]
You need to pass onChange the setInitialData callback so the changed data will be saved to the state
