### ISSUE TITLE
Is there a way to select an entire Row/Column?

### ISSUE THREAD

**Issue by LoboChristopher** [iddan/react-spreadsheet#103]
I'm using this component on my project and would love to know more about how to use React Spreadsheet, is there any documentation?

**Comment by iddan** [comment]
Hey, thank you for trying React Spreadsheet. currently, there is no way. Would it be useful for you to have this functionality?

**Comment by SithlordChris666** [comment]
Yes, it would be great to have a way to select an entire row or column, because I want to select the entire Row/Column and save it in an object and manipulate the data.

**Comment by iddan** [comment]
I got a little stuck with the implementation as I can't find the time to continue. I'd be happy to get some help from the community with this
