### ISSUE TITLE
Limited exports from index file

### ISSUE THREAD

**Issue by cpv123** [iddan/react-spreadsheet#106]
I noticed that on master branch there are a number of exports from `src/index.ts` that aren't in the most recent version 0.5.0.

Can you release another version from master with these additional exports?

There are some other exports that I also need (that aren't on master either) which I will include in a PR. FYI the other exports I need are the `DataViewer` and `DataEditor` components.

Great library overall though 👍

**Comment by iddan** [comment]
Hey @cpv123, sure thing.

**Comment by cpv123** [comment]
@iddan thanks! I'll raise a small PR with those additional exports in the next couple of hours.

**Comment by iddan** [comment]
I released `0.5.1` with the latest master. Once your changes are integrated I can release another version

**Comment by cpv123** [comment]
@iddan I've just raised this PR for the exports: https://github.com/iddan/react-spreadsheet/pull/107

**Comment by iddan** [comment]
I’ve published a new version with your changes
