### ISSUE TITLE
Paste single cell value into multiple cells

### ISSUE THREAD

**Issue by cpv123** [iddan/react-spreadsheet#109]
Hey @iddan 👋

Any idea how difficult it would be to allow a single cell value to be copied and then pasted into multiple (highlighted) cells? 

For example:
1. Copy a single cell
2. Highlight a range of cells
3. Paste
4. Have the single cell value pasted into each highlighted cell 

<div display="flex">
<img width="379" alt="Screen Shot 2564-02-26 at 17 19 52" src="https://user-images.githubusercontent.com/35846795/109288011-e8038f00-7856-11eb-93d9-44b1d9586e0f.png">
<img width="332" alt="Screen Shot 2564-02-26 at 17 20 03" src="https://user-images.githubusercontent.com/35846795/109288016-e9cd5280-7856-11eb-993a-6820b7ea2560.png">
</div>

If you don't see any immediate issues with implementing this, I will give it a try myself and raise a PR. I guess that this would be a good place for me to start? https://github.com/iddan/react-spreadsheet/blob/master/src/actions.ts#L138

**Comment by iddan** [comment]
Hey @cpv123 , it shouldn't be very difficult. You are correct. This would be the right place to start

**Comment by dominik-zeglen** [comment]
Is there any update about this? It feels like one of core functions of spreadsheet that is missing here
