### ISSUE TITLE
TypeScript error : Declaration or statement expected. TS1128

### ISSUE THREAD

**Issue by thinkanddoit** [iddan/react-spreadsheet#111]
I want to use this library on my project but I had TS1128 error.

Can I get some help?

**Comment by thinkanddoit** [comment]
Perhaps, Does it not support typescript yet?

**Comment by iddan** [comment]
Can you provide a code sandbox?

**Comment by cpv123** [comment]
@iddan is this related to https://github.com/iddan/react-spreadsheet/pull/108?

Can you do a 0.5.3 release?

**Comment by iddan** [comment]
I am not sure. I'll release

**Comment by iddan** [comment]
The latest master is released in version 0.5.4

**Comment by yencolon** [comment]
I ran into this issue too, the error occurs when trying to export types in index.d.ts, I'm using typescript 3.7.2, any workaround?

**Comment by iddan** [comment]
Which version are you using?

**Comment by yencolon** [comment]
@iddan Hi, thanks for answering, as I said in the message I'm using typescript version 3.7.2.

**Comment by iddan** [comment]
I meant, which version of React Spreadsheet are you using?

**Comment by yencolon** [comment]
The last one, 0.5.10
