### ISSUE TITLE
remove focus on spreadsheet cell

### ISSUE THREAD

**Issue by PratyushaTN** [iddan/react-spreadsheet#118]
Hi,

I've incorporated spreadsheet in my project. But, I noticed that after clicking on any of the cells within the spreadsheet and then click outside it, like somewhere else on the page does not remove the focus and the cell remains highlighted.

is there a way to remove the focus off of the cell when we click outside the spreadsheet?

**Comment by iddan** [comment]
Fixed in `react-spreadsheet@0.5.17`
