### ISSUE TITLE
Implement dark mode

### ISSUE THREAD

**Issue by AndresPerezTesela** [iddan/react-spreadsheet#126]
I guess it can be done from outside the library with CSS descendants. But It would be nice to have an easily enabling dark mode.

**Comment by iddan** [comment]
Great idea, pull requests are welcome

**Comment by iddan** [comment]
Check the implementation in react-spreadsheet-website: https://github.com/iddan/react-spreadsheet-site/blob/master/src/pages/styles.module.css

**Comment by iddan** [comment]
Added `darkMode` prop in `react-spreadsheet@0.5.20`
