### ISSUE TITLE
How to change row and column naming?

### ISSUE THREAD

**Issue by altwarg** [iddan/react-spreadsheet#127]
I want to change naming of rows and columns.
For example, instead of "A", "B", etc. column names I would like to set my own. The same for rows.

Any suggestions?

**Comment by iddan** [comment]
You can provide a custom `RowIndicator` and `ColumnIndicator` components

**Comment by carolinabsts** [comment]
Hi!

Is there a example?
The implementation isn't clear, really sorry. 
I need to iterate an array of names for each column, but I have only managed to create a custom component without the possibility of its name being dynamic. 

I would appreciate a small example, if possible. 

Thanks!

**Comment by altwarg** [comment]
@carolinabsts, the easier way to set custom row and column labels is to use `rowLabels` and `columnLabels` properties:

```jsx
import React from 'react';
import Spreadsheet from 'react-spreadsheet';

export const CustomSpreadsheet = () => {
  const data = [
    [{ value: 'Vanilla' }, { value: 'Chocolate' }],
    [{ value: 'Strawberry' }, { value: 'Cookies' }],
  ];

  const rowLabels = ['First row', 'Second row'];

  const columnLabels = ['First column', 'Second column'];

  return (
    <Spreadsheet
      data={data}
      rowLabels={rowLabels}
      columnLabels={columnLabels}
    />
  );
};
```

And the result:
![image](https://user-images.githubusercontent.com/34391398/119768119-c4d19580-bec0-11eb-9952-5fbba9978765.png)
