### ISSUE TITLE
Cell turns undefined on view mode

### ISSUE THREAD

**Issue by victoralessandro** [iddan/react-spreadsheet#134]
Steps to reproduce
1. Select a cell on view mode.
2. Press the backspace key.

The cells turn into undefined and lose the object shape { value: "" } having this data as result

[{value: "" }, undefined, {value: ""}]

**Comment by iddan** [comment]
I think it deletes the content of the cell. Isn't it the behaviour of other spreadsheet applications (e.g. Excel, Google Sheets?)

**Comment by iddan** [comment]
Closing due to lack of response.
