### ISSUE TITLE
Data not Displayed correctly

### ISSUE THREAD

**Issue by khushibalodi** [iddan/react-spreadsheet#136]
if there is an uneven number of columns in a row, all of them are not displayed. Does it require to have the same no. of columns in each row?
Attached screenshots for reference.
code:
![image](https://user-images.githubusercontent.com/52121551/124713014-9e6e3380-df1d-11eb-8346-6d349822aa16.png)

output:
![image](https://user-images.githubusercontent.com/52121551/124712931-85658280-df1d-11eb-8793-810b99a2b77e.png)

**Comment by iddan** [comment]
The first item in the data array (i.e. the first row's data) must have the number of items (i.e. columns) that the spreadsheet should present because otherwise the component would need to iterate through all the rows in the data array and check for the maximum columns number.
