### ISSUE TITLE
Change Selected Cell Color

### ISSUE THREAD

**Issue by HamidShaikh1499** [iddan/react-spreadsheet#152]
Thanks for this component. and is there an interface or method to change color of selected cell in spreadsheet component.

if have mind providing code or a link to understand how to change color of selected cell

**Comment by iddan** [comment]
Hey, thank you for trying React Spreadsheet. You can customise the colour of a selected cell by providing a Cell component. Each cell receives the `selected` boolean prop that indicates whether it is selected or not. Refer to the custom cell story in `Spreadsheet.stories.tx`

**Comment by HamidShaikh1499** [comment]
thank you @iddan for your answer I closed it again thanks for replying...
