### ISSUE TITLE
Matrix data reset when I useState 

### ISSUE THREAD

**Issue by Electacle** [iddan/react-spreadsheet#157]
Hello, I have a rather major problem:
When I change the data on one or more cells of the table and I use a useState for another use on a form that has absolutely nothing to do with the table... The cells I had modified are then reset with the original values of the table.

Maybe I'm missing something, I'm only starting with react recently. 

If someone could enlighten me, I would be very grateful!
Have a nice day !

**Comment by iddan** [comment]
Hey! Can you provide a code sandbox that reproduces your issue?

**Comment by Electacle** [comment]
Yes, I forgot about the onChange. Now the problem is solved. The example brings a lot of information, thanks a lot for the answers
