### ISSUE TITLE
Performant 

### ISSUE THREAD

**Issue by kamaldlk** [iddan/react-spreadsheet#16]
@iddan is there any update for Performant. I'm so curious about this.

**Comment by kamaldlk** [comment]
@iddan any update on this :(

**Comment by iddan** [comment]
Hey, the component is pretty performant. What precisely are you curious about?

**Comment by kamaldlk** [comment]
virtualized columns and rows while scrolling

**Comment by iddan** [comment]
Oh.. Currently we have great performance without virtualisation. But virtualisation support is expected. We are very open to PRs regarding this. But for most use cases the current performance of the component should do.

**Comment by kamaldlk** [comment]
ok Bro Thanks :)
