### ISSUE TITLE
Test Components

### ISSUE THREAD

**Issue by iddan** [iddan/react-spreadsheet#162]
- [x] Row         
 - [x] Cell        
     - [x] Component
     - [x] enhance
 - [x] DataViewer  
 - [x] DataEditor  
 - [x] ActiveCell  - Requires State Context
 - [x] Copied      - Requires State Context
 - [x] Selected    - Requires State Context
 - [x] Spreadsheet - In Progress

**Comment by iddan** [comment]
Now that the simple components are tested I’m unsure how to continue.
On one hand, the use of unistore is temporary and I would really rather to maintain as little code as possible relating to it. On the other hand: React Context Selectors, which I planned that will replace unistore, are not arriving any time soon and they will be restricted to React 18 anyway. 
So I see two options:
 - Migrate the code base to a modern, standard and stable state managers (Recoile and Redux come first to my mind)
 - Test the code as is with unistore

**Comment by iddan** [comment]
Another good option may be using [React Tracked](https://react-tracked.js.org) which seems to introduce the least amount of new concepts

**Comment by iddan** [comment]
With #165 `useContextSelector` is now used for state sharing between components. Now, components are more easily testable.

**Comment by govind15496** [comment]
Hello @iddan, can I work on this ?

**Comment by iddan** [comment]
Hey @govind15496 I would love that!

**Comment by govind15496** [comment]
can you explain problem little bit more @iddan ?

**Comment by iddan** [comment]
We aim to have unit tests for each component. Currently, all the small components have simple tests. But the spreadsheet is still lacking some tests. You can run the tests and see the coverage to understand which parts are still lacking tests.
