### ISSUE TITLE
While using Sreadsheet i got error

### ISSUE THREAD

**Issue by HamidShaikh1499** [iddan/react-spreadsheet#164]
I don't know why this error appear and i tried to solve it but i can't because i didn't understand what exactly error is.

**Error**
![image](https://user-images.githubusercontent.com/50068289/132802707-c6fd2360-82ff-42d6-82b7-76ce39f3b72a.png)

Please update the following components: c, r || what the mean by this line thats why i didn;t understand it  

Node.js Version v14
ReactJs Version v17
React-Spreadsheet v0.5.14

**Comment by HamidShaikh1499** [comment]
https://github.com/iddan/react-spreadsheet/issues/142

I found this issue i hope this will solve as soon as possible @React-Spreadsheet is awesome Component

**Comment by iddan** [comment]
Thank you, we are working on this. Closing as it is a duplicate. Please track #142
