### ISSUE TITLE
im getting this page after running 

### ISSUE THREAD

**Issue by kamaldlk** [iddan/react-spreadsheet#17]
![screenshot 2018-10-23 at 7 02 59 pm](https://user-images.githubusercontent.com/9652523/47364199-4dc73580-d6f6-11e8-9cca-62a759b3af4a.png)

**Comment by iddan** [comment]
Can you share your usage?

**Comment by jseremba** [comment]
Getting the same

**Comment by iddan** [comment]
How is your environment set up? Are you using Create React App or a custom webpack / babel settings?

**Comment by iddan** [comment]
Closing for no response
