### ISSUE TITLE
How to Change Selected Cell Color

### ISSUE THREAD

**Issue by HamidShaikh1499** [iddan/react-spreadsheet#174]
Sorry @iddan I didn't found any thing from your docs and also your answer 

> Hey, thank you for trying React Spreadsheet. You can customise the colour of a selected cell by providing a Cell component. Each cell receives the selected boolean prop that indicates whether it is selected or not. Refer to the custom cell story in Spreadsheet.stories.tx

How to use Cell component and how to change color of cell using cell component please provide link

i want to compare first row data with suggest data if found, founded cell color should be changed(greenColor)

**Comment by iddan** [comment]
Hey @HamidShaikh1499, I’m currently on vacation. I’ll try to issue your question on the next weekend

**Comment by HamidShaikh1499** [comment]
Hey @iddan, Thank you sir for replying!

**Comment by HamidShaikh1499** [comment]
I got my answer from documentation we can change cell color by using html tag in cell component like below

`const [data,setData] = useState([{value:<h1 className="bg-green-300 p-12 text-white">Hi @iddan </h1},{value:"you"}])
<Spreadsheet data={data} />`

**NOTE in value i removed <></> this because this is Browser it renders html tag use proper tag with <></>**

use tag instead of string in value prop it is simple and cell color changed 

Please add Question label in this issue and thank you 

**Please @iddan Add color Prop in cell component to change color of cell LIKE {value:"",color:"green"}**

**Comment by HamidShaikh1499** [comment]
@iddan Please Close and add question label and thank you this awesome Component ReactJS
