### ISSUE TITLE
[Feature] Either describing all cells, either describe only row and column

### ISSUE THREAD

**Issue by c0ncentus** [iddan/react-spreadsheet#181]
Hi.

Indeed when you make a excel forms with json schema i spend few days to make this happen.

## Exemple + some interface extract from my personnal work
because i want to make lines, columns and make operation to colorize all the line 2 on blue, make the line 1 readable only; 
make the column A readableOnly ... 

```ts
export interface BuildArrayCellSchema {
    type: "column"
    pathProp: string[],
    propsRoot?: string[]
    columnBefore: CellExcel[][],
    columnAfter: CellExcel[][],
    isReturnToTheLine?: boolean
}

export interface BuildLinesSchema {
    type: "line",
    lineAfter: CellExcel[][],
}
type SomeColors = "forestgreen" | "crimson" | "deeppink" | "darkturquoise" | "darkmagenta" | "navy" | "olive" | "gray" | "indigo" | "orangered" | "darkorange" | "black" | "dodgerblues";

export interface OptionExcel {
    isAdd: boolean
    isDelete: boolean,
    readonly: number[],
    objColor: { colorized: number[], color?: SomeColors }[]
}
```

## Why
it would be great to have internal tools to achieve this because it's painfull to build with cells. In the most case describe cells is waste of time rather describes lines or columns.

**Comment by iddan** [comment]
Sorry, but I'm not sure I understand the issue here. Can you please rephrase?
