### ISSUE TITLE
Advanced examples of use of the components

### ISSUE THREAD

**Issue by nfgoto** [iddan/react-spreadsheet#194]
Where can I find practical examples of use cases of the components ?
Any advanced examples of spreadsheet customization (fixed width and height editor with inside scroll for overflowing cells, etc.) ?
I don't find this in the documentation.
Did I miss it ?

**Comment by iddan** [comment]
Please check out https://github.com/iddan/react-spreadsheet/blob/master/src/stories/Spreadsheet.stories.tsx
