### ISSUE TITLE
Deploy storybook

### ISSUE THREAD

**Issue by dominik-zeglen** [iddan/react-spreadsheet#231]
I don't think it goes without any notice that docs for this library are... not that good, but its storybook is quite well done. Maybe it'd help to deploy it somewhere? I doubt that I'm the only one that had to clone this repo and build sb locally, especially that I've seen links to stories' source code a few times in responses here. 
You can use vercel or something like that for autodeploy.

**Comment by iddan** [comment]
Gave an attempt tonight. It wasn't easy. Storybook makes it pretty hard to build under a subpath and docusaurus doesn't make it easy to serve storybook from its static folder...

**Comment by vipersils** [comment]
FWIW it would already help new people to even have instructions to run the storybook locally to even know that it exists ;) I've been stumbling around a while with the docs...

**Comment by iddan** [comment]
Great feedback! Would love a PR

**Comment by vipersils** [comment]
FWIW I haven't got it up and running yet, didnt allocate much time to it though

**Comment by iddan** [comment]
Storybook is now available at: https://iddan.github.io/react-spreadsheet/storybook/
