### ISSUE TITLE
Paste should pad columns as well as rows

### ISSUE THREAD

**Issue by whsu00** [iddan/react-spreadsheet#232]
`react-spreadsheet` automatically expands rows when data is pasted in, but not columns:

<img width="339" alt="Screen Shot 2022-05-09 at 11 15 42 AM" src="https://user-images.githubusercontent.com/9411368/167471924-1105f374-d6a3-4e7c-9df1-1aacd803013d.png">
<img width="339" alt="Screen Shot 2022-05-09 at 11 15 46 AM" src="https://user-images.githubusercontent.com/9411368/167471925-79f3c404-e343-4d46-a5bf-9ab3f81cc9e5.png">
<img width="339" alt="Screen Shot 2022-05-09 at 11 15 50 AM" src="https://user-images.githubusercontent.com/9411368/167471929-9a658e03-d52a-40dd-bb3e-aa0fa4cf809e.png">

While on Google Sheets, pasting data with more rows or columns than in the spreadsheet will expand the spreadsheet:

<img width="293" alt="Screen Shot 2022-05-09 at 11 10 09 AM" src="https://user-images.githubusercontent.com/9411368/167471119-b1831188-0854-4fe2-91d9-d9dbb1910693.png">
<img width="293" alt="Screen Shot 2022-05-09 at 11 10 14 AM" src="https://user-images.githubusercontent.com/9411368/167471120-82e790ad-d163-48de-a731-8ed48eb42099.png">
<img width="339" alt="Screen Shot 2022-05-09 at 11 10 20 AM" src="https://user-images.githubusercontent.com/9411368/167471122-969e6611-41bb-4d36-baf3-8063f0152713.png">

https://github.com/iddan/react-spreadsheet/blob/7a5e6a23731714c3a0151c8b15b4024da623854f/src/matrix.ts#L215-L226

**Comment by iddan** [comment]
Thank you for the detailed report! PRs are welcome

**Comment by Interlogy** [comment]
Anyone fixed it already?

**Comment by iddan** [comment]
Fixed in react-spreadsheet@0.7.7
