### ISSUE TITLE
Column/Row Indicator Props export?

### ISSUE THREAD

**Issue by rhit-jancad** [iddan/react-spreadsheet#238]
I was working with this on a fairly large project I am working on, but I realized I was using an old version. When I updated it, it gave me a few errors, and upon further inspection, I realized that my row and column indicator props were throwing errors, saying that column and label didn't exist on type Prop. I was declaring my column indicators like this: `const ColumnIndicator = React.memo(function ColumnIndicator({column, label,}: ColumnIndicatorProps<CashbookSectionCellData>)`  

This is still very new to me, so is there any reason why this would break from an update?

**Comment by iddan** [comment]
Seems like I forgot to expose the type for `ColumnIndicatorProps`. I'll update.

**Comment by iddan** [comment]
Fixed in `react-spreadsheet@0.7.5`

**Comment by rhit-jancad** [comment]
Awesome, thank you so much!
