### ISSUE TITLE
Copy / paste doesn't convert zero and false values properly

### ISSUE THREAD

**Issue by zsiswick** [iddan/react-spreadsheet#250]
When I copy a cell containing `0` or `false` values, the new data passed to the Spreadsheet onChange method appears to convert them to empty strings. However, these values are meaningful and I need them to remain as they were. 

When entering this data directly into the cells, the values seem to be honored but copy / paste doesn't seem to work the same.

https://user-images.githubusercontent.com/7780183/188491950-5d43b016-2699-4bed-8762-8a4f89577884.mov

**Comment by iddan** [comment]
Thank you @zsiswick for reporting. I'll try to address this but I don't have a lot of time for working on React Spreadsheet right now. Would love to review a PR though.
