### ISSUE TITLE
re-rendering all cells

### ISSUE THREAD

**Issue by BatistaYuri** [iddan/react-spreadsheet#258]
I noticed that sometimes the screen was freezing a little, using React Dev Tools, clicking on a cell, sometimes re-rendering all cells

![Captura de tela de 2022-10-17 11-17-39](https://user-images.githubusercontent.com/38445234/196201368-1e707f32-636a-4e8b-bada-4d5b21c17654.png)

**Comment by iddan** [comment]
When does it happen? Can you provide a reproduction please?
