### ISSUE TITLE
Removing getComputedValue is breaking change

### ISSUE THREAD

**Issue by matt2112** [iddan/react-spreadsheet#298]
Hello, just to let you know that `v0.7.8` -> `v0.8.0` is a breaking change for us as it removes `getComputedValue`, but I don't see it mentioned in the release notes (just a reference to `getBindingsForCell` which we're not using).

I don't see a reason why we need to upgrade to v8 urgently for now, but I take it there was a good reason for removing `getComputedValue`? The bit of our codebase that uses it hasn't been touched in a while so I'm not super familiar with it, but it seems we're using it for interfacing with `hot-formula-parser`.

**Comment by iddan** [comment]
Thank you @matt2112 for pointing this out. I have replaced the internal implementation to use a different library that is more maintained (hot-formula-parser got deprecated). Could you please provide your use for `getComputedValue`?

**Comment by matt2112** [comment]
Hi @iddan, so basically we're hooking into the `callCellValue` event and applying some formatting like this:

```ts
formulaParser.on(
  'callCellValue',
  (coord: FormulaParserCoords, done: (val: unknown) => void) => {
    ...
    const value = getComputedValue({ cell, formulaParser })
    const formattedValue = doStuff(value)
    return done(formattedValue)
  }
)
```

And then elsewhere we do something like:

```ts
const getRecomputedValues = (data: DataType[]) => {
  ...
  const recomputed = data.map((dp) => {
    const newVal = getComputedValue({
      cell: convertDatapointToCell(dp, { isForDisplay: false }),
      formulaParser,
    })
    return newVal
  )}
  ...
  return { recomputed, ... }
})
```

Which we later use to sync with our state in a useEffect:

```ts
    const { recomputed } = getRecomputedValues(data)
    updateDatapoints(recomputed)
```

There's probably a better way, but that's the gist of it.

**Comment by iddan** [comment]
Okay so anyway you’d be affected by the switch to another formula parser as I understand it. If you’d like you can contact me in person and I’ll try to help with the migration

**Comment by matt2112** [comment]
Thanks @iddan, that's very kind of you to offer. Probably won't be soon but I'll give you a shout if we need help.

Mainly the reason I raised this was just to flag the release notes could be clearer for anyone else who might be using `getComputedValue` in a similar way. Will close the issue though.

**Comment by iddan** [comment]
Updated the release notes
