### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by yallie** [iddan/react-spreadsheet#30]
Hi, the component looks great! Does it support TypeScript?
I don't see *.d.ts typings anywhere...

**Comment by iddan** [comment]
Not yet, but I'll be very glad to help to make it happen!

**Comment by dboskovic** [comment]
@iddan would you be down to accept a flow -> TS refactor of the code?

**Comment by iddan** [comment]
I do! It would be wonderful. But it's important the types richness will be preserved.

**Comment by dboskovic** [comment]
Amazing. We’re using it here at flatfile.io and would ❤️ to take on the TS migration

**Comment by iddan** [comment]
This is amazing! Feel free to reach out if you need any help

**Comment by chadlavi-casebook** [comment]
@dboskovic @iddan anything happening on this? one of my colleagues suggested this library for a project we have coming up, but without TS support it's not feasible.

**Comment by iddan** [comment]
I'll accept incoming pull requests.
