### ISSUE TITLE
Ability to navigate rows with Tab without changing what column Enter returns to

### ISSUE THREAD

**Issue by garcia** [iddan/react-spreadsheet#301]
There's a nice ergonomic behavior of popular spreadsheet apps (Google Sheets, Excel, LibreOffice Calc) where pressing Enter returns to the last column that was selected *without* the Tab key. This makes it easy to fill a range of columns for multiple rows using only the keyboard.

For example, typing `foo<Tab>bar<Tab>baz<Enter>` does this:

![Recording 2023-05-31 at 18 51 52](https://github.com/iddan/react-spreadsheet/assets/1851864/dbf3d0ab-1fb5-429b-91a7-c024cccbe7a5)

Great library, by the way :)

**Comment by iddan** [comment]
Thank you @garcia, this is a welcome improvement for the library.

**Comment by iddan** [comment]
Should be fixed with the new version
