### ISSUE TITLE
Merge Cells Support

### ISSUE THREAD

**Issue by LeifAndersen** [iddan/react-spreadsheet#308]
Issue number #98 asked if there was a way to merge two cells together so that one row might have a double wide cell.

The response said that the answer was no, but potentially possible with CSS.

Unfortunately the original person who asked seems to have lost interest and the issue was closed.

I am actually interested in this (using a CSS hack is potentially okay). Since I can't just re-open the issue, I'm making a new one here.

**Comment by iddan** [comment]
Were you not able to get the desired result w CSS?

**Comment by LeifAndersen** [comment]
I'm...err...actually no entirely sure _how_ to go about doing it with CSS.

**Comment by iddan** [comment]
You can remove the borders between the cells that you want to display as merged.
