### ISSUE TITLE
Can't run demo project

### ISSUE THREAD

**Issue by dangxquang** [iddan/react-spreadsheet#31]
![image](https://user-images.githubusercontent.com/49668846/57919774-bad52f00-78c3-11e9-8d53-36f93fd5482a.png)
Have this error when loading component. Something is wrong when build

**Comment by iddan** [comment]
Thank you. I'll try to get around it as soon as possible

**Comment by DovahBrownies** [comment]
Bump.

**Comment by iddan** [comment]
Fixed in `react-spreadsheet@0.4.33`

**Comment by DovahBrownies** [comment]
Nice one!
