### ISSUE TITLE
Overriding formula parser no longer possible?

### ISSUE THREAD

**Issue by Yomantica** [iddan/react-spreadsheet#320]
I was looking at the latest release and thus far I am unable to override the formula parser used in the spreadsheet. My use case: I want to limit the functions that can be used and alter the behavior of some others. With the 0.7 releases this was possible with the formulaParser prop on the spreadsheet introduced in [61](https://github.com/iddan/react-spreadsheet/pull/61).

Is there another way I can override this in the 0.8 release?

**Comment by iddan** [comment]
Hey, the underlying formula parser has changed in the last release and I wasn't sure whether to expose it. The implementation is based on https://github.com/LesterLyu/fast-formula-parser. Will it help you to access it?

**Comment by Yomantica** [comment]
Thanks for the response. I think I'll work on a PR making the formula parser overridable again since the implemented formula parser is nog longer maintained (see [issue](https://github.com/LesterLyu/fast-formula-parser/issues/57)).

**Comment by Yomantica** [comment]
See [PR 329](https://github.com/iddan/react-spreadsheet/pull/329) :D
