### ISSUE TITLE
Loading data from external source functions aren't evaluated

### ISSUE THREAD

**Issue by alexgriffithsdev** [iddan/react-spreadsheet#323]
Hi there,

Firstly, thanks a lot for this project - it is one of the best and easiest to use spreadsheet components I have found.

I am facing a small issue when saving and loading the spreadsheet. When I load the spreadsheet's data, if a cell has a formula in it the formula is not evaluated and instead shows as '=A1*10'.

How can I ensure formulas are evaluated when loading data?

Thanks

**Comment by iddan** [comment]
Hey @alexgriffithsdev, thank you for the feedback. Can you provide a minimal Code Sandbox to demonstrate your issue?

**Comment by LeoDT** [comment]
there is only `react-spreadsheet@0.7.8` on Code Sandbox, but it's easy to reproduce

```
<Spreadsheet data={[[{ value: 1 }, { value: 1 }, { value: '=A1+B1' }]]} />
```

the formula is not evaluated on initializing

@iddan

**Comment by Yomantica** [comment]
Would love to see this one fixed too! @LeoDT maybe create a PR to show what you did? Might be the quickest and easiest way for @iddan :)

**Comment by davidsharff** [comment]
This would be great and is a blocker for my use case. Unless there is another way for me to propagate an (evaluated) formula to other cells automatically.

**Comment by iddan** [comment]
Hey, I'm working on a solution here: https://github.com/iddan/react-spreadsheet/pull/335 if someone wants to help me out fixing the last failing test that would be of great help

**Comment by iddan** [comment]
Resolved in react-spreadsheet@0.8.5

**Comment by LeoDT** [comment]
@iddan 

Thank you for your hard work. I just updated and saw the results, and found another issue, it should be related to this one.

The initial formulas are evaluated except that reference a cell with a formula in. For example, A1 is 1, B1 is 2, C1 is `=A1+B1`, D1 is `=C1`. The result should be `1 2 3 3`, but now it's `1 2 3 =A1+B1`.

code sandbox is here: https://codesandbox.io/s/affectionate-tharp-xtdywn?file=/src/App.js

**Comment by iddan** [comment]
#343 solves the provided issue
