### ISSUE TITLE
On handle change, expose the result of the formula.

### ISSUE THREAD

**Issue by siliconjungle** [iddan/react-spreadsheet#338]
Currently when a cell has a formula in it, it visually displays the result of the formula, but it doesn't expose that value in the handleChange method.

For controlled spreadsheets this is a core feature. Are there currently any workarounds for this?

**Comment by siliconjungle** [comment]
> Hey, great idea. Can you elaborate a little on your use case?

I'm building a code notebook where the spreadsheet is one of the block types. I'd like to be able to both query the result of a cell or the value of a cell but currently the handleChange method only exposes the value.

**Comment by iddan** [comment]
Got you. I currently don't have the capacity to work on this feature but I'm open for PRs and can try to get to it when I'll have some free time.

**Comment by siliconjungle** [comment]
I'll see if I can find some time to give it a crack. :)

**Comment by BALURAM1226** [comment]
@siliconjungle, I'm actively working on resolving the CI failure issue. If it is successfully resolved and the merge is successful, you will receive the exposed data.

**Comment by iddan** [comment]
Closed with #379
