### ISSUE TITLE
onCellCommmit is not called on cut/paste

### ISSUE THREAD

**Issue by ben-pr-p** [iddan/react-spreadsheet#34]
I'm relying on onCellCommit to send changes to my database – right now, it's not called on paste or cut.

Is the best way to implement this to paste `props.onCellCommit` to paste and cut (at https://github.com/iddan/react-spreadsheet/blob/master/src/Spreadsheet.js#L162 and https://github.com/iddan/react-spreadsheet/blob/master/src/Spreadsheet.js#L155) respectively, and have them call onCellCommit directly for the affected cells from there?

**Comment by iddan** [comment]
Yes!

**Comment by iddan** [comment]
Fixed in last versions
