### ISSUE TITLE
Cells are using the wrong values

### ISSUE THREAD

**Issue by siliconjungle** [iddan/react-spreadsheet#340]
When a cell references another cell, it's using the value in the cell rather than the result (which is inconsistent with other spreadsheets like Google sheets & Excel).

The case also hasn't been handled where there is a circular dependency. It currently leads to the program crashing.

**Comment by iddan** [comment]
Thank you for reporting @siliconjungle. Can you please provide some test cases, please? I would love to fix the behaviour but need some more concrete examples.

**Comment by iddan** [comment]
Can you validate it reproduces in the latest version (react-spreadsheet@0.8.6)? I made some fixes to the formula evaluation that I think may solve your problem.

**Comment by iddan** [comment]
I'm closing this as I'm pretty sure the bug is fixed. @siliconjungle if it still repeats with the new version please update and I'll reopen the issue.
