### ISSUE TITLE
Could not find a declaration file for module 'react-spreadsheet'. 

### ISSUE THREAD

**Issue by Salamit** [iddan/react-spreadsheet#35]
Hi, I get this error on the following line

import Spreadsheet from 'react-spreadsheet';

```
Could not find a declaration file for module 'react-spreadsheet'. 'handRecog/node_modules/react-spreadsheet/dist/SpreadsheetStateProvider.js' implicitly has an 'any' type.
  Try `npm install @types/react-spreadsheet` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-spreadsheet';`ts(7016)
```

**Comment by iddan** [comment]
Hey, thank you for using React Spreadsheet. Currently, we don't TypeScript declarations but I would be happy to accept a PR for them and help with coding them. Unfortunately, I don't have the time to do it on my own at the time.

**Comment by iddan** [comment]
This is actually a duplicate of #30
