### ISSUE TITLE
Error when editing a formula in a cell

### ISSUE THREAD

**Issue by BournazosHarry** [iddan/react-spreadsheet#352]
Hi and thanks for the awesome work so far!

When I'm editing a cell that already contains a formula e.g. =SUM(A1:A3)
If I want to change let's say A3 to A4 and I start by deleting 3, the current formula looks like =SUM(A1:A)
I get an error from react:

![image](https://github.com/iddan/react-spreadsheet/assets/1215635/8fef0427-c500-4003-8c2e-cee8aa5a8535)

Looking into the DataViewer I didn't see any handling of such case, I believe that it has to do with my implementation of storing these changes from a wrapping component which may lead to a re-render.

It would be convenient if the library ignored this in that case so it wouldn't crash. After editing it could show the #REF! or other error etc.

**Comment by iddan** [comment]
Solved in react-spreadsheet@0.9.4
