### ISSUE TITLE
Bug: Typing `==` immediately crashes the spreadsheet

### ISSUE THREAD

**Issue by AntonyGarand** [iddan/react-spreadsheet#371]
Hey!
Was looking at spreadsheet options for React and while playing around on the playground trying out formulas, I noticed a bug where if you mistype `==`, it immediately crashed the whole page.
![image](https://github.com/iddan/react-spreadsheet/assets/9059487/40563e2e-a0c2-4f62-a034-73de093965dd)
This is not if it is submitted as-is, but immediately as it is typed, which seems like an odd behavior: I would expect invalid formulas to be scoped to a single cell and display an error message if the formula was invalid, not crash the whole thing while still editing the formula.

Thought I'd report it as it seems like a fairly low hanging fruit!

**Comment by iddan** [comment]
Solved in react-spreadsheet@0.9.4
