### ISSUE TITLE
/Users/iddan/react-spreadsheet-tmp/ is not found.

### ISSUE THREAD

**Issue by tourze** [iddan/react-spreadsheet#38]
![image](https://user-images.githubusercontent.com/13899502/60067276-9e3adb00-973c-11e9-9fff-860bf297f859.png)
![image](https://user-images.githubusercontent.com/13899502/60067297-ac88f700-973c-11e9-9f20-b0149ddb9481.png)

**Comment by iddan** [comment]
Oh no! Let me check that

**Comment by iddan** [comment]
Fixed in `react-spreadsheet@0.4.33`
