### ISSUE TITLE
license scan is failing for one of the components used ua-parser-js

### ISSUE THREAD

**Issue by SantoshRaoBlr** [iddan/react-spreadsheet#44]
I am not sure if this is a concern, could this be validated

**Comment by iddan** [comment]
It's not a direct dependency, but I try to use the minimum required dependencies for this component. I guess it has to do with formulas. Do you use formulas?

**Comment by SantoshRaoBlr** [comment]
Yes was mainly looking to use formulae

**Comment by iddan** [comment]
So, unfortunately I don't have a lot to do with it right now as it's a license of a dependency.
