### ISSUE TITLE
Unistore is trying to access devtools on production build

### ISSUE THREAD

**Issue by mjackstone6** [iddan/react-spreadsheet#47]
I am trying to get the "Getting Started" demo working but I am running into a security error.
Please see the attached codesandbox example: https://codesandbox.io/s/flamboyant-hopper-gkh0h

Any ideas on how to fix this?

**Comment by iddan** [comment]
Looks good for me. What browser are you using?

**Comment by mjackstone6** [comment]
It seems to work in create-react-app on my desktop; however, on codesandbox it triggers the error I mentioned. I get the following message when I click the error on codesandbox using Chrome: "Unable to open 'devtools.js': File not found (file:///sandbox/node_modules/unistore/devtools.js)." 
On FireFox I get a more detailed error message for the above: "Permission denied to access property "__REDUX_DEVTOOLS_EXTENSION__" on cross-origin object".

**Comment by iddan** [comment]
Oh, it has to do with unistore redux devtools integration. It's odd it fails on production though. Definitely a bug.

**Comment by iddan** [comment]
Fixed in 0.4.40
