### ISSUE TITLE
flatMap should get 2 parameters: array and a function, but here I dont see any function paramter

### ISSUE THREAD

**Issue by ueeieiie** [iddan/react-spreadsheet#5]
https://github.com/iddan/react-spreadsheet/blob/fadb80d1a5d1a6027d92189b1ab88538e371c2ea/src/matrix.js#L68

**Comment by iddan** [comment]
`_range(endPoint.row, startPoint.row)` returns Array, `row =>` is a function expression.  What's missing?

**Comment by ueeieiie** [comment]
My mistake.. :)
