### ISSUE TITLE
Copy/Paste does not work with Excel or Google Spreadsheets

### ISSUE THREAD

**Issue by IronSean** [iddan/react-spreadsheet#51]
Copy and Paste functionality doesn't work with other Spreadsheet applications.

Values are copied as comma separated values, instead of tab separated values. This means that copying a set of four cells like this
`a``b`
`c``d`
pastes into excel and Google Sheets like this
`a, b`
`c, d`.

And values copied from the external applications will not paste into the `react-spreadsheet`, instead the last thing that was copied locally on react-spreadsheet, not what was copied from an external application. This is true for both Tab separated List and Comma Separated Value on the system clipboard.

**Comment by iddan** [comment]
Hello, thank you for giving React Spreadsheet a try and reporting the issue in such detail. I’ll try to fix this ASAP. I’m currently on vacation so I’ll probably get around it next week. If you need a fix very urgently and need a PR review I can do that as well.
