### ISSUE TITLE
Flow errors

### ISSUE THREAD

**Issue by morloy** [iddan/react-spreadsheet#58]
There are quite some unsolved Flow errors. Any plans to fix them soon?

Also, the exported component in `SpreadsheetStateProvider.js` has many props marked as required even though they are not.

**Comment by iddan** [comment]
I think we'll move to TypeScript instead. Not clear when is it going to happen yet.

**Comment by iddan** [comment]
Resolved with

**Comment by iddan** [comment]
I refactored the project to TypeScript, so type checking should be much better now
