### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by cambo2015** [iddan/react-spreadsheet#65]
Hello,
 I am wanting to style the elements in the table with text-alignment, and other CSS customization.
I tried to pass CSS classes via className and styles but neither worked for me. Any help on how to do this would be great! Thanks!

**Comment by iddan** [comment]
Hey, can you provide some sample code of what you tried to do?

**Comment by cambo2015** [comment]
I'd love to. I'm not able to at the moment though but will asap. Thank you for your fast reply.

**Comment by cambo2015** [comment]
Sorry for the slow response. Here is what I tried <Spreadsheet data={data}  className={classes.root}/>.
I also tried passing in custom styles via styles={customStyles}

**Comment by abiliocoelho** [comment]
@iddan Good night, how can I style the component? I need it to be centralized and occupy the entire area of the external container. thank you very much
