### ISSUE TITLE
Customize header value ?

### ISSUE THREAD

**Issue by revskill10** [iddan/react-spreadsheet#68]
Thanks for such elegant library !

I just have a question though. In my case, i need the header to be grouped or customized with title. Does the library support now or not yet ?

So in place of A,B,C, i want it to be like

```
Profile Detail                  | Column 1 | Colum 2
First name | Last Name
... row data
```

**Comment by iddan** [comment]
Yes, please see the ColumnLabels example for reference https://github.com/iddan/react-spreadsheet/blob/master/__fixtures__/withColumnLabels.js
