### ISSUE TITLE
Error compatibility with React 16.x version

### ISSUE THREAD

**Issue by ad798** [iddan/react-spreadsheet#70]
Thank your for this excelent spreadsheet in React.

I had two errors in console after compiling in dev mode with React 16.13.1 (created with create-react-app):

Error 1:
`index.js:1 Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: c, r

Learn more about this warning here: https://fb.me/react-legacy-context
    in r (created by SpreadsheetStateProvider)
    in SpreadsheetStateProvider (at Component.js:104)
    in Component (at App.js:100)
    in div (at App.js:99)
    in article (at App.js:96)
    in div (at App.js:95)
    in div (at App.js:94)
    in div (at App.js:84)
    in div (at App.js:83)
    in App (at src/index.js:27)
    in StrictMode (at src/index.js:26)`

Error 2:
`Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: c
console.<computed> @ index.js:1
`
I would appreciate a solution to this. I really enjoyed this project to be included in a bigger one. Thank you very much.

**Comment by iddan** [comment]
Hey, thank you for posting this issue a while back. I am currently trying every weekend to slightly improve the situation of this. I have refactored the easiest components to hooks and am now working on converting the rest. Also, I'll try to replace unistore with something a little more modern in the near future.

**Comment by llermaly** [comment]
Bump on this! , I really love this library but I don't have the knowledge to help fixing this. @iddan I would like to support this improvement and the library donating. Is that option available? Regards and congrats

**Comment by iddan** [comment]
Hey, @llermaly I made big progress with this as I updated the code to TypeScript which will ease further maintenance.

**Comment by iddan** [comment]
Should be solved by now with the latest version.
