### ISSUE TITLE
more user friendly and efficient api

### ISSUE THREAD

**Issue by r3wt** [iddan/react-spreadsheet#75]
The api is rather unfriendly to the user. its also inefficient for use case of custom rendering, as you are duplicating the renders on each row of data

A better api:

1. replace `columnLabels` with `displayRules`, which has type as follows:

```tsx
type DisplayRule = { label: string; key: string; view:DataViewer, edit: DataEditor };
```
As you can see, rather than creating many references of DataViewer/Editor throughout our data, we can just have it in display rules. you can also use this to change the column order, irrespective of its natural key ordering in javascript.

2. change `data` to accept `Array<any>` instead of `Matrix<{value:any,DataViewer?:any,DataEditor?:any}>`

example what this might look like from a developer perspective:

```jsx
<Spreadsheet 
    displayRules={[
      { label: 'Name', key: 'name' },
      { label:'Date', key:'date', view: renderDateView, edit: renderDateInput }
      { label: 'Amount', key: 'amount', view: renderAmountView, edit: renderAmountInput  },
    ]}
    data={[
      { name: 'Hank Hill', date:'07-26-2020', amount: 93.50 },
      { name: 'Herbert Farnsworth', date:'07-25-2020', amount: 196.25 },
      { name: 'Bruce Wayne', date:'07-24-2020', amount: 7.36 },
    ]}
  />
```

Would you be receptive to such a change at all?

**Comment by iddan** [comment]
I would like to keep the specific cell data viewer and editor. But I agree that defining `DataViewer` and `DataEditor` for a whole column can be useful.
Can you provide a suggestion that does not break the current API?
