### ISSUE TITLE
request: ability to disable editing

### ISSUE THREAD

**Issue by r3wt** [iddan/react-spreadsheet#76]
i need to be able to disable editing, but still allow viewing, including highlighting and selecting the cell content to copy.

**Comment by iddan** [comment]
You can provide `readOnly` property to cells to create this behaviour. Will that work for your use case?

**Comment by r3wt** [comment]
@iddan yes, it should. thank you for info. any plan to document the props?

**Comment by iddan** [comment]
Definitely on my bucket list. Unfortunately, I don't have much time to invest in this package nowadays but help with that would be very welcome
