### ISSUE TITLE
Update State

### ISSUE THREAD

**Issue by abiliocoelho** [iddan/react-spreadsheet#77]
Hello, how do I update the status after editing a cell?

**Comment by iddan** [comment]
Can you please give an example? I'm not sure I understand your question

**Comment by abiliocoelho** [comment]
Thanks for the answer. when i change a cell, how do i update the value in the state?

**Comment by iddan** [comment]
As described in the README you have the `onChange` property which you can use the get cell updates and `data` property which you can provide the updated data. Please see: https://github.com/iddan/react-spreadsheet/blob/master/__fixtures__/Controlled.js

**Comment by abiliocoelho** [comment]
It was exactly that, thank you very much for your attention. have a great day
