### ISSUE TITLE
Incorrect evaluation for values that are derived from other derived values

### ISSUE THREAD

**Issue by meetmangukiya** [iddan/react-spreadsheet#79]
Try, 
A1 = `2`
A2 = `=A1 * 2`
A3 = `=A2 * 2`

**Comment by mgotze** [comment]
Hi, any idea when this fix will be published?
Thanks!

**Comment by iddan** [comment]
Thank you for reporting the bug! At the moment I don't have the capacity to solve it but I would be glad to review a PR.
