### ISSUE TITLE
Setup CI for CD of gh-pages

### ISSUE THREAD

**Issue by meetmangukiya** [iddan/react-spreadsheet#82]
maybe with master version of react-spreadsheet?

**Comment by iddan** [comment]
That can be great 😄

**Comment by meetmangukiya** [comment]
I think the first step is getting the gatsby code in this repo. Currently, you have just pushed the build manually to the gh-pages I think without the source being in the repo somewhere.

**Comment by iddan** [comment]
The code is currently managed here: https://github.com/iddan/react-spreadsheet-site

**Comment by iddan** [comment]
Done
