### ISSUE TITLE
Wrong coordinates passed to onCellCommit?

### ISSUE THREAD

**Issue by victoralessandro** [iddan/react-spreadsheet#83]
The coordinates passed to the onCellCommit function are not the coordinates from the committed cell. 
Example flow: Editing row: 0, cell: 0, press enter, and the onCellCommit function is called with coordinates row: 1, cell: 0, not row: 0, cell: 0. 

Maybe it could be useful to have both coordinates passed to the function, the coordinates for the committed cell and the coordinates for the cell the user has moved to.

**Comment by iddan** [comment]
Thank you for reporting

**Comment by mgodf** [comment]
It's hack-y but a workaround is to hold a reference to the `Spreadsheet` in the containing component, and take the coordinates from `prevState`

**e.g.**,
```js
<Spreadsheet data={data} ref={(s) => {window.spreadsheet_ref= s}} 
    onCellCommit={
        (prevCell, nextCell, coords) => {
            let prev_coords = window.spreadsheet_ref.prevState.active;
        }
}/>
```

**Comment by aitorCerecetoGlovoApp** [comment]
is this already fixed? I have problems to set a matrix

**Comment by parkertomatoes** [comment]
@mgodf does this workaround still work for you? I successfully used it after getting burned by this issue, but I recently started getting typescript errors on the "ref" property of `<Spreadsheet>`

I saw that this recent commit converts `<Spreadsheet>` to a hooks-based functional component:
https://github.com/iddan/react-spreadsheet/commit/45d452c04deff586e9c4b21d340f417605bc0473#diff-041be12dc5e08d26a5c3a7b9628767b60842d24bfff3c5163aa024c8b4cdb572

One consequence is that `ref` only gets automatically added to props for class components, not function components:
https://reactjs.org/docs/refs-and-the-dom.html

**Comment by cristinamarin22** [comment]
> @mgodf does this workaround still work for you? I successfully used it after getting burned by this issue, but I recently started getting typescript errors on the "ref" property of `<Spreadsheet>`
> 
> I saw that this recent commit converts `<Spreadsheet>` to a hooks-based functional component: [45d452c#diff-041be12dc5e08d26a5c3a7b9628767b60842d24bfff3c5163aa024c8b4cdb572](https://github.com/iddan/react-spreadsheet/commit/45d452c04deff586e9c4b21d340f417605bc0473#diff-041be12dc5e08d26a5c3a7b9628767b60842d24bfff3c5163aa024c8b4cdb572)
> 
> One consequence is that `ref` only gets automatically added to props for class components, not function components: https://reactjs.org/docs/refs-and-the-dom.html

Having the same issue! Please help

**Comment by rifkyniyas** [comment]
@parkertomatoes Yes. Now receiving the error as below.

> Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

**Comment by chasingmaxwell** [comment]
I just opened a PR (#246) which passes `lastChanged` instead of `active` for the coordinates to `onCellCommit`. I _think_ this will resolve the issue.
