### ISSUE TITLE
Only numbers 

### ISSUE THREAD

**Issue by abiliocoelho** [iddan/react-spreadsheet#85]
How can I configure the cells to be numbers only?

**Comment by iddan** [comment]
Hey @abiliocoelho, thank you for trying React Spreadsheet. Can you please elaborate on what do you mean by "numbers only"? Do you mean the user will be allowed to input numbers only?

**Comment by abiliocoelho** [comment]
> Hey @abiliocoelho, thank you for trying React Spreadsheet. Can you please elaborate on what do you mean by "numbers only"? Do you mean the user will be allowed to input numbers only?

Yes, i need input only numbers on the cells

**Comment by iddan** [comment]
Alright, then you can provide a custom `DataEditor` prop and use an input that allows numbers only. See https://stackoverflow.com/questions/43067719/how-to-allow-only-numbers-in-textbox-in-reactjs for reference.

**Comment by abiliocoelho** [comment]
Sorry for the insistence, but am I doing something wrong? I need cells to only accept numbers and floating points. Thank you very much

![Captura de Tela 2020-10-24 às 18 32 04](https://user-images.githubusercontent.com/17254884/97094038-67721f00-1627-11eb-8d31-3dc296794ff5.png)

**Comment by abiliocoelho** [comment]
Sorry, I'm not getting the cell to accept just numbers. Could you tell what is incorrect in the code? Thank you very much

![Captura de Tela 2020-10-25 às 10 26 49](https://user-images.githubusercontent.com/17254884/97108518-e493a780-16ac-11eb-80e1-edc430bfc6f7.png)
![Captura de Tela 2020-10-25 às 10 28 14 (2)](https://user-images.githubusercontent.com/17254884/97108520-e6f60180-16ac-11eb-9aed-28dd5e893a62.png)

**Comment by iddan** [comment]
I'll check the code later. If you can, please provide a CodeSandBox so I can debug it faster

**Comment by abiliocoelho** [comment]
Thank you very much

<iframe src="https://codesandbox.io/embed/fervent-violet-6t400?fontsize=14&hidenavigation=1&theme=dark"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="fervent-violet-6t400"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>

**Comment by abiliocoelho** [comment]
@iddan, I don't know how to thank you, thank you very much.

[![Edit fervent-violet-6t400](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fervent-violet-6t400?fontsize=14&hidenavigation=1&theme=dark)

**Comment by abiliocoelho** [comment]
> I'll check the code later. If you can, please provide a CodeSandBox so I can debug it faster

@iddan, thank you very much.

[![Edit throbbing-bash-bbth8](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/throbbing-bash-bbth8?fontsize=14&hidenavigation=1&theme=dark)
