### ISSUE TITLE
Cells are editable with readOnly = true & mode = view

### ISSUE THREAD

**Issue by victoralessandro** [iddan/react-spreadsheet#87]
when a cell has the readOnly attribute set to true if you select a cell and press the backspace key the value is erased

**Comment by iddan** [comment]
Thank you! I'll try to go get around this as soon as possible.

**Comment by victoralessandro** [comment]
A workaorund I found  is to pass a onkeyDow function and check if the cell has the readonly css class
```const handleKeyDown = (e) => {
    if (e.target.className.includes("readonly")) {
      e.preventDefault();
      return;
    }
  };```

**Comment by felipehimself** [comment]
This issue is still happening. 

The workaround I found was to wrapper to Spreadsheet component with a div and set pointer events to none using CSS.
