### ISSUE TITLE
Programatically select/unselect cells

### ISSUE THREAD

**Issue by mgodf** [iddan/react-spreadsheet#89]
Is there some way to programatically set the cell selection?

Thank you!

**Comment by iddan** [comment]
Hey, thank you for trying React Spreadsheet. Currently no, but I can make it happen. Would you like me to try?

**Comment by iddan** [comment]
Quick update on that: with the progress made in #161 I think selection is going to be more sophisticated than an array of points (as it used to be until now). I think this feature is better be implemented after a breaking change that would change `onSelect` to receive `Selection` and it can introduce a new prop called `selected` that accepts `Selection`

**Comment by iddan** [comment]
Another update: now that #161 is merged we can go ahead to make the breaking change that `onSelect` receives `Selection` and introduce a new `selected` prop. Might require improving the implementation of the `Selection` data type for better API to the consumer.
