### ISSUE TITLE
how to delete a row or column

### ISSUE THREAD

**Issue by emacsbliss** [iddan/react-spreadsheet#96]
not sure if it's supported, but didn't find anything from the readme?

if it's supported, where can I find an example?

Thanks a lot for the help!

**Comment by iddan** [comment]
Hey @emacsbliss there is a story that does just that https://github.com/iddan/react-spreadsheet/blob/master/src/stories/Spreadsheet.stories.tsx#L23

**Comment by emacsbliss** [comment]
thanks a lot, I'm not familiar with typescript.
From the example, I think it's triggered via button click..

wonder is it possible to achieve that via context menu(right mouse click) on a particular
row or column so that information is already known based on event?

**Comment by iddan** [comment]
Yes, you only need to delete the cells from the data and the component will reflect that.

**Comment by emacsbliss** [comment]
I guess I mainly look for how to make the component handle context menu event so it knows which row/column the right click happened which then can pass to callback?

**Comment by iddan** [comment]
Oh.. you can use https://github.com/vkbansal/react-contextmenu. It can be integrated into this library as well.

**Comment by emacsbliss** [comment]
thanks!
but I felt it's not possible to integrate react-contextmenu into this library, maybe I missed something..

my issue is so far seems I can only change DataViewer for the cell, but upon rendering, whatever element I returned from my custom DataViewer(which is the place I hook into react-contextmenu) is the inner children of a `td` element and that seems never trigger the context menu..

any help would be greatly appreciated!
